
import { DocumentMetadata, SummaryData } from '../types';

/**
 * Utility functions for contract analysis operations
 */

export const createDocumentMetadata = (file: File): DocumentMetadata => {
  return {
    id: `doc-${Date.now()}`,
    name: file.name,
    type: file.type.includes('pdf') ? 'PDF' : 'Document',
    uploadDate: new Date().toISOString(),
    status: 'processing',
    version: '1.0',
    versionDate: new Date().toISOString(),
    size: file.size,
    category: 'Legal Agreement'
  };
};

export const createPlaceholderSummary = (): SummaryData => {
  return {
    summary: [
      {
        title: "Contract Overview",
        content: "Contract analysis requires connection to AI services. Please ensure proper API keys are configured for document analysis."
      },
      {
        title: "Parties Involved",
        content: "Party information would be extracted from the actual contract"
      },
      {
        title: "Key Terms",
        content: "Terms would be identified through AI analysis"
      },
      {
        title: "Obligations",
        content: "Obligations would be extracted from the contract text"
      },
      {
        title: "Risk Assessment",
        content: "Risk assessment would be performed on the actual contract"
      },
      {
        title: "Recommendations",
        content: "AI-generated recommendations would appear here"
      }
    ],
    disclaimer: "This analysis is generated by artificial intelligence and is provided for informational purposes only. It does not constitute legal advice and should not be relied upon for legal decisions. Always consult with a qualified attorney for professional legal guidance."
  };
};

export const extractTextFromFile = async (file: File): Promise<string> => {
  return new Promise((resolve) => {
    const reader = new FileReader();
    reader.onload = (e) => {
      const result = e.target?.result as string;
      if (file.type === 'text/plain') {
        resolve(result);
      } else {
        // For PDF and other formats, provide placeholder that indicates real document processing is needed
        resolve(`Document uploaded: ${file.name}\n\nTo enable full AI analysis, please ensure your contract is in a supported format. The system will extract and analyze the actual contract content.`);
      }
    };
    
    if (file.type === 'text/plain') {
      reader.readAsText(file);
    } else {
      reader.readAsDataURL(file);
    }
  });
};

export const validateFileType = (file: File): boolean => {
  const allowedTypes = ['text/plain', 'application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'];
  return allowedTypes.includes(file.type);
};

export const formatFileSize = (bytes: number): string => {
  if (bytes === 0) return '0 Bytes';
  const k = 1024;
  const sizes = ['Bytes', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
};
