
import { AIRequestOptions, AIResponse } from './useDocumentAIBase';
import { DocumentAnalysisResponse } from './types';

/**
 * Clean markdown formatting from AI response text
 */
const cleanMarkdownText = (text: string): string => {
  if (!text) return '';
  
  return text
    // Remove all markdown headers (###, ##, #) but keep the text
    .replace(/#{1,6}\s+([^\n]*)/g, '$1')
    // Remove all bold/italic markdown formatting (**text**, *text*, ***text***)
    .replace(/\*{1,3}([^*\n]+)\*{1,3}/g, '$1')
    // Remove standalone asterisks at start of lines (but keep content dashes and numbers)
    .replace(/^\s*\*+\s*/gm, '')
    // Remove markdown bullet points but preserve numbered lists and content dashes
    .replace(/^\s*\*\s+/gm, '')
    // Remove horizontal rules (multiple dashes) but keep single dashes in content
    .replace(/^-{3,}$/gm, '')
    .replace(/^={3,}$/gm, '')
    // Clean up any remaining standalone asterisks
    .replace(/(?<!\w)\*+(?!\w)/g, '')
    // Clean up multiple spaces and newlines
    .replace(/\s{2,}/g, ' ')
    .replace(/\n{3,}/g, '\n\n')
    // Ensure proper spacing after periods and colons
    .replace(/([.:])\s*\n/g, '$1\n\n')
    .trim();
};

/**
 * Clean markdown from analysis content recursively
 */
const cleanAnalysisContent = (content: any): any => {
  if (typeof content === 'string') {
    return cleanMarkdownText(content);
  }
  
  if (Array.isArray(content)) {
    return content.map(cleanAnalysisContent);
  }
  
  if (content && typeof content === 'object') {
    const cleaned: any = {};
    for (const [key, value] of Object.entries(content)) {
      cleaned[key] = cleanAnalysisContent(value);
    }
    return cleaned;
  }
  
  return content;
};

interface UseDocumentAnalysisOperationsProps {
  processAIRequest: (
    operation: string,
    options: AIRequestOptions
  ) => Promise<AIResponse | null>;
}

/**
 * Hook for document analysis operations
 */
export const useDocumentAnalysisOperations = ({ processAIRequest }: UseDocumentAnalysisOperationsProps) => {
  
  /**
   * Analyze a document with AI using real AI service
   */
  const analyzeDocument = async (
    documentId: string,
    documentVersionId: string,
    analysisType: string
  ): Promise<DocumentAnalysisResponse | null> => {
    const response = await processAIRequest('analyze_document', {
      documentId,
      documentVersionId,
      content: '',
      context: { analysisType }
    });
    
    if (response && response.analysis) {
      const cleanedAnalysis = typeof response.analysis === 'string' 
        ? JSON.parse(response.analysis) 
        : response.analysis;
      
      return {
        analysis: {
          type: analysisType,
          content: cleanAnalysisContent(cleanedAnalysis)
        },
        disclaimer: response.disclaimer || 'This analysis was generated by AI and should be reviewed by a professional.'
      };
    }
    
    return null;
  };
  
  /**
   * Generate a real summary of the document using AI
   */
  const summarizeDocument = async (
    documentId: string,
    documentVersionId: string
  ): Promise<any> => {
    const response = await processAIRequest('summarize_document', {
      documentId,
      documentVersionId,
      content: 'Full document summary'
    });
    
    // Clean the response if it contains markdown
    if (response && typeof response.summary === 'string') {
      response.summary = cleanMarkdownText(response.summary);
    }
    
    return response;
  };
  
  return {
    analyzeDocument,
    summarizeDocument
  };
};
