
import { AIRequestOptions, AIResponse } from './useDocumentAIBase';
import { DocumentAnalysisResponse } from './types';

interface UseDocumentAnalysisOperationsProps {
  processAIRequest: (
    operation: string,
    options: AIRequestOptions
  ) => Promise<AIResponse | null>;
}

/**
 * Hook for document analysis operations
 */
export const useDocumentAnalysisOperations = ({ processAIRequest }: UseDocumentAnalysisOperationsProps) => {
  
  /**
   * Analyze a document with AI using real AI service
   */
  const analyzeDocument = async (
    documentId: string,
    documentVersionId: string,
    analysisType: string
  ): Promise<DocumentAnalysisResponse | null> => {
    const response = await processAIRequest('analyze_document', {
      documentId,
      documentVersionId,
      content: '',
      context: { analysisType }
    });
    
    if (response && response.analysis) {
      return {
        analysis: {
          type: analysisType,
          content: typeof response.analysis === 'string' 
            ? JSON.parse(response.analysis) 
            : response.analysis
        },
        disclaimer: response.disclaimer || 'This analysis was generated by AI and should be reviewed by a professional.'
      };
    }
    
    return null;
  };
  
  /**
   * Generate a real summary of the document using AI
   */
  const summarizeDocument = async (
    documentId: string,
    documentVersionId: string
  ): Promise<any> => {
    return processAIRequest('summarize_document', {
      documentId,
      documentVersionId,
      content: 'Full document summary'
    });
  };
  
  return {
    analyzeDocument,
    summarizeDocument
  };
};
