
import { AIRequestOptions, AIResponse } from './useDocumentAIBase';
import { MilestoneGenerationResponse } from './types';

interface UseMilestoneGenerationOperationsProps {
  processAIRequest: (
    operation: 'generate_milestones',
    options: AIRequestOptions
  ) => Promise<AIResponse | null>;
}

/**
 * Hook for milestone generation operations - now using real AI
 */
export const useMilestoneGenerationOperations = ({ processAIRequest }: UseMilestoneGenerationOperationsProps) => {
  
  /**
   * Generate milestones for a deal based on deal type using real AI
   */
  const generateMilestones = async (dealType: string): Promise<MilestoneGenerationResponse | null> => {
    const response = await processAIRequest('generate_milestones', {
      content: dealType,
    });
    
    if (response && response.milestones) {
      return {
        milestones: response.milestones,
        disclaimer: response.disclaimer || 'These milestones were generated by AI and should be reviewed and customized as needed.'
      };
    }
    
    return null;
  };
  
  return {
    generateMilestones,
  };
};
