
import { fetchDealContextData } from './utils/deal-context-fetcher.ts';
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

export async function handleGenerateMilestones(
  dealId: string,
  userId: string,
  context: any,
  openai: any
) {
  // Initialize Supabase client
  const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
  const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
  const supabase = createClient(supabaseUrl, supabaseKey);

  try {
    console.log(`🎯 Starting milestone generation for deal ${dealId} with context:`, context);
    console.log(`👤 User ID: ${userId}`);
    
    // Fetch comprehensive deal data
    const dealContext = await fetchDealContextData(dealId);
    const { deal, documents, participants, milestones: existingMilestones } = dealContext;
    
    // Get deal type from context (passed from frontend) or deal data
    const dealType = context?.dealType || deal.deal_type || 'Asset Sale';
    
    // Create a comprehensive prompt for milestone generation
    const prompt = `You are an AI assistant helping to generate appropriate milestones for a business deal. Based on the following deal information, generate a comprehensive list of milestones that are typical for this type of transaction.

Deal Information:
- Title: ${deal.title || 'Not specified'}
- Business Name: ${deal.business_legal_name || 'Not specified'}
- Deal Type: ${dealType}
- Status: ${deal.status}
- Asking Price: ${deal.asking_price ? `$${deal.asking_price.toLocaleString()}` : 'Not specified'}
- Reason for Selling: ${deal.reason_for_selling || 'Not specified'}
- Target Completion Date: ${deal.target_completion_date || 'Not specified'}
- Current Health Score: ${deal.health_score}/100

Participants: ${participants.map(p => `${p.role}: ${p.profiles?.name || 'Unknown'}`).join(', ')}

Documents: ${documents.map(d => `${d.name} (${d.type})`).join(', ') || 'No documents uploaded yet'}

Existing Milestones: ${existingMilestones.length > 0 ? existingMilestones.map(m => m.title).join(', ') : 'None'}

Please generate 5-8 realistic and actionable milestones for this ${dealType} transaction. Each milestone should:
1. Be specific to this type of deal
2. Have a clear, actionable title
3. Include a detailed description of what needs to be accomplished
4. Be ordered logically in the typical sequence they would occur

Consider typical phases like: initial documentation, due diligence, legal review, financial verification, regulatory approvals, contract negotiation, closing preparations, and completion.

Respond with a JSON object containing an array of milestones, each with 'name', 'description', and 'order' properties. Keep descriptions practical and specific to business acquisitions.`;

    // Call OpenAI to generate milestones
    const completion = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        {
          role: "system",
          content: "You are an expert in business deal management and mergers & acquisitions. Generate realistic, actionable milestones for business transactions. Always respond with valid JSON."
        },
        {
          role: "user",
          content: prompt
        }
      ],
      temperature: 0.7,
      max_tokens: 1500
    });

    const response = completion.choices[0].message.content;
    console.log('OpenAI response for milestones:', response);

    // Parse the response and extract milestones
    let generatedMilestones;
    try {
      // Clean the response to handle markdown-wrapped JSON
      let cleanedResponse = response.trim();
      if (cleanedResponse.startsWith('```json')) {
        cleanedResponse = cleanedResponse.replace(/^```json\s*/, '').replace(/\s*```$/, '');
      } else if (cleanedResponse.startsWith('```')) {
        cleanedResponse = cleanedResponse.replace(/^```\s*/, '').replace(/\s*```$/, '');
      }
      
      const parsed = JSON.parse(cleanedResponse);
      generatedMilestones = parsed.milestones || parsed;
      
      // Ensure each milestone has the required properties
      generatedMilestones = generatedMilestones.map((milestone: any, index: number) => ({
        name: milestone.name || milestone.title || `Milestone ${index + 1}`,
        description: milestone.description || 'No description provided',
        order: milestone.order || index + 1
      }));
      
    } catch (parseError) {
      console.error('Failed to parse OpenAI response as JSON:', parseError);
      
      // Fallback: generate default milestones based on deal type
      generatedMilestones = generateDefaultMilestones(dealType);
    }

    console.log(`Generated ${generatedMilestones.length} milestones for deal ${dealId}`);
    
    return {
      milestones: generatedMilestones,
      disclaimer: "These milestones were generated by AI based on your deal information. Please review and customize them as needed for your specific situation."
    };
    
  } catch (error) {
    console.error('Error in handleGenerateMilestones:', error);
    
    // Fallback: return default milestones instead of failing
    const dealType = context?.dealType || 'Asset Sale';
    const fallbackMilestones = generateDefaultMilestones(dealType);
    
    return {
      milestones: fallbackMilestones,
      disclaimer: "AI generation temporarily unavailable. These are standard milestones for your deal type. Please customize as needed."
    };
  }
}

// Helper function to generate default milestones when AI fails
function generateDefaultMilestones(dealType: string) {
  const commonMilestones = [
    {
      name: "Initial Documentation Review",
      description: "Gather and review all essential business documents including financial statements, contracts, and legal documentation.",
      order: 1
    },
    {
      name: "Due Diligence Phase",
      description: "Conduct comprehensive due diligence covering financial, legal, and operational aspects of the business.",
      order: 2
    },
    {
      name: "Financial Verification",
      description: "Verify financial records, revenue streams, and assess the true financial health of the business.",
      order: 3
    },
    {
      name: "Legal Review and Compliance",
      description: "Complete legal review of all contracts, ensure regulatory compliance, and identify any legal risks.",
      order: 4
    },
    {
      name: "Contract Negotiation",
      description: "Negotiate final terms, conditions, and purchase agreement details between all parties.",
      order: 5
    },
    {
      name: "Closing Preparations",
      description: "Prepare all closing documents, coordinate with attorneys, and schedule the closing meeting.",
      order: 6
    },
    {
      name: "Transaction Completion",
      description: "Execute final agreements, transfer ownership, and complete all regulatory filings.",
      order: 7
    }
  ];

  // Customize first milestone based on deal type
  if (dealType.toLowerCase().includes('asset')) {
    commonMilestones[0] = {
      name: "Asset Inventory and Valuation",
      description: "Create comprehensive inventory of all assets included in the sale and obtain professional valuations.",
      order: 1
    };
  } else if (dealType.toLowerCase().includes('stock')) {
    commonMilestones[0] = {
      name: "Share Structure Analysis",
      description: "Review current share structure, shareholder agreements, and corporate governance documents.",
      order: 1
    };
  }

  return commonMilestones;
}
