
import { fetchDealContextData } from './utils/deal-context-fetcher.ts';

export async function handleSuggestNextAction(
  dealId: string,
  openai: any
) {
  try {
    console.log(`🎯 Starting next action suggestion for deal ${dealId}`);
    
    // Fetch comprehensive deal data
    const dealContext = await fetchDealContextData(dealId);
    const { deal, documents, participants, milestones } = dealContext;
    
    // Calculate milestone progress
    const totalMilestones = milestones.length;
    const completedMilestones = milestones.filter(m => m.status === 'completed').length;
    const inProgressMilestones = milestones.filter(m => m.status === 'in_progress').length;
    const blockedMilestones = milestones.filter(m => m.status === 'blocked').length;
    const notStartedMilestones = milestones.filter(m => m.status === 'not_started').length;
    
    // Create a comprehensive prompt for next action suggestion
    const prompt = `You are an AI assistant helping to suggest the next best action for a business deal. Based on the following deal information, suggest a specific, actionable next step to move the deal forward.

Deal Information:
- Title: ${deal.title || 'Not specified'}
- Business Name: ${deal.business_legal_name || 'Not specified'}
- Status: ${deal.status}
- Health Score: ${deal.health_score}/100
- Asking Price: ${deal.asking_price ? `$${deal.asking_price.toLocaleString()}` : 'Not specified'}
- Target Completion: ${deal.target_completion_date || 'Not specified'}

Milestone Progress:
- Total Milestones: ${totalMilestones}
- Completed: ${completedMilestones}
- In Progress: ${inProgressMilestones}
- Blocked: ${blockedMilestones}
- Not Started: ${notStartedMilestones}

Current Milestones:
${milestones.map(m => `- ${m.title} (${m.status})`).join('\n')}

Participants: ${participants.map(p => `${p.role}: ${p.profiles?.name || 'Unknown'}`).join(', ')}

Documents: ${documents.length > 0 ? documents.map(d => `${d.name} (${d.type})`).join(', ') : 'No documents uploaded yet'}

Based on this information, suggest ONE specific next action that would have the highest impact on moving this deal forward. Consider:
1. Current bottlenecks or blocked milestones
2. Missing documentation or information
3. Participant engagement and communication needs
4. Risk mitigation opportunities
5. Timeline acceleration possibilities

Provide a clear, actionable recommendation with specific steps the user can take immediately.`;

    // Call OpenAI to generate next action suggestion
    const completion = await openai.chat.completions.create({
      model: "gpt-4.1-2025-04-14",
      messages: [
        {
          role: "system",
          content: "You are an expert business deal advisor. Provide specific, actionable recommendations to help move deals forward efficiently. Be concise but thorough in your suggestions."
        },
        {
          role: "user",
          content: prompt
        }
      ],
      temperature: 0.7,
      max_tokens: 800
    });

    const suggestion = completion.choices[0].message.content;
    console.log('Next action suggestion generated successfully');
    
    return {
      suggestion: suggestion,
      dealStatus: deal.status,
      healthScore: deal.health_score,
      disclaimer: "This suggestion is generated by AI based on your current deal data. Please review and adapt as needed for your specific situation."
    };
    
  } catch (error) {
    console.error('Error in handleSuggestNextAction:', error);
    throw new Error('Failed to suggest next action');
  }
}
